// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/assistant/embedded/v1alpha1/embedded_assistant.proto

package com.google.assistant.embedded.v1alpha1;

public interface ConverseConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.assistant.embedded.v1alpha1.ConverseConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * *Required* Specifies how to process the subsequent incoming audio.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha1.AudioInConfig audio_in_config = 1;</code>
   */
  boolean hasAudioInConfig();
  /**
   * <pre>
   * *Required* Specifies how to process the subsequent incoming audio.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha1.AudioInConfig audio_in_config = 1;</code>
   */
  com.google.assistant.embedded.v1alpha1.AudioInConfig getAudioInConfig();
  /**
   * <pre>
   * *Required* Specifies how to process the subsequent incoming audio.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha1.AudioInConfig audio_in_config = 1;</code>
   */
  com.google.assistant.embedded.v1alpha1.AudioInConfigOrBuilder getAudioInConfigOrBuilder();

  /**
   * <pre>
   * *Required* Specifies how to format the audio that will be returned.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha1.AudioOutConfig audio_out_config = 2;</code>
   */
  boolean hasAudioOutConfig();
  /**
   * <pre>
   * *Required* Specifies how to format the audio that will be returned.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha1.AudioOutConfig audio_out_config = 2;</code>
   */
  com.google.assistant.embedded.v1alpha1.AudioOutConfig getAudioOutConfig();
  /**
   * <pre>
   * *Required* Specifies how to format the audio that will be returned.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha1.AudioOutConfig audio_out_config = 2;</code>
   */
  com.google.assistant.embedded.v1alpha1.AudioOutConfigOrBuilder getAudioOutConfigOrBuilder();

  /**
   * <pre>
   * *Required* Represents the current dialog state.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha1.ConverseState converse_state = 3;</code>
   */
  boolean hasConverseState();
  /**
   * <pre>
   * *Required* Represents the current dialog state.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha1.ConverseState converse_state = 3;</code>
   */
  com.google.assistant.embedded.v1alpha1.ConverseState getConverseState();
  /**
   * <pre>
   * *Required* Represents the current dialog state.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha1.ConverseState converse_state = 3;</code>
   */
  com.google.assistant.embedded.v1alpha1.ConverseStateOrBuilder getConverseStateOrBuilder();
}
