// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/assistant/embedded/v1alpha1/embedded_assistant.proto

package com.google.assistant.embedded.v1alpha1;

/**
 * <pre>
 * The top-level message sent by the client. Clients must send at least two, and
 * typically numerous `ConverseRequest` messages. The first message must
 * contain a `config` message and must not contain `audio_in` data. All
 * subsequent messages must contain `audio_in` data and must not contain a
 * `config` message.
 * </pre>
 *
 * Protobuf type {@code google.assistant.embedded.v1alpha1.ConverseRequest}
 */
public  final class ConverseRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.assistant.embedded.v1alpha1.ConverseRequest)
    ConverseRequestOrBuilder {
  // Use ConverseRequest.newBuilder() to construct.
  private ConverseRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ConverseRequest() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ConverseRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.assistant.embedded.v1alpha1.ConverseConfig.Builder subBuilder = null;
            if (converseRequestCase_ == 1) {
              subBuilder = ((com.google.assistant.embedded.v1alpha1.ConverseConfig) converseRequest_).toBuilder();
            }
            converseRequest_ =
                input.readMessage(com.google.assistant.embedded.v1alpha1.ConverseConfig.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.google.assistant.embedded.v1alpha1.ConverseConfig) converseRequest_);
              converseRequest_ = subBuilder.buildPartial();
            }
            converseRequestCase_ = 1;
            break;
          }
          case 18: {
            converseRequestCase_ = 2;
            converseRequest_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.assistant.embedded.v1alpha1.AssistantProto.internal_static_google_assistant_embedded_v1alpha1_ConverseRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.assistant.embedded.v1alpha1.AssistantProto.internal_static_google_assistant_embedded_v1alpha1_ConverseRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.assistant.embedded.v1alpha1.ConverseRequest.class, com.google.assistant.embedded.v1alpha1.ConverseRequest.Builder.class);
  }

  private int converseRequestCase_ = 0;
  private java.lang.Object converseRequest_;
  public enum ConverseRequestCase
      implements com.google.protobuf.Internal.EnumLite {
    CONFIG(1),
    AUDIO_IN(2),
    CONVERSEREQUEST_NOT_SET(0);
    private final int value;
    private ConverseRequestCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ConverseRequestCase valueOf(int value) {
      return forNumber(value);
    }

    public static ConverseRequestCase forNumber(int value) {
      switch (value) {
        case 1: return CONFIG;
        case 2: return AUDIO_IN;
        case 0: return CONVERSEREQUEST_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ConverseRequestCase
  getConverseRequestCase() {
    return ConverseRequestCase.forNumber(
        converseRequestCase_);
  }

  public static final int CONFIG_FIELD_NUMBER = 1;
  /**
   * <pre>
   * The `config` message provides information to the recognizer that
   * specifies how to process the request.
   * The first `ConverseRequest` message must contain a `config` message.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha1.ConverseConfig config = 1;</code>
   */
  public com.google.assistant.embedded.v1alpha1.ConverseConfig getConfig() {
    if (converseRequestCase_ == 1) {
       return (com.google.assistant.embedded.v1alpha1.ConverseConfig) converseRequest_;
    }
    return com.google.assistant.embedded.v1alpha1.ConverseConfig.getDefaultInstance();
  }
  /**
   * <pre>
   * The `config` message provides information to the recognizer that
   * specifies how to process the request.
   * The first `ConverseRequest` message must contain a `config` message.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha1.ConverseConfig config = 1;</code>
   */
  public com.google.assistant.embedded.v1alpha1.ConverseConfigOrBuilder getConfigOrBuilder() {
    if (converseRequestCase_ == 1) {
       return (com.google.assistant.embedded.v1alpha1.ConverseConfig) converseRequest_;
    }
    return com.google.assistant.embedded.v1alpha1.ConverseConfig.getDefaultInstance();
  }

  public static final int AUDIO_IN_FIELD_NUMBER = 2;
  /**
   * <pre>
   * The audio data to be recognized. Sequential chunks of audio data are sent
   * in sequential `ConverseRequest` messages. The first `ConverseRequest`
   * message must not contain `audio_in` data and all subsequent
   * `ConverseRequest` messages must contain `audio_in` data. The audio bytes
   * must be encoded as specified in `AudioInConfig`.
   * Audio must be sent at approximately real-time (16000 samples per second).
   * An error will be returned if audio is sent significantly faster or
   * slower.
   * </pre>
   *
   * <code>bytes audio_in = 2;</code>
   */
  public com.google.protobuf.ByteString getAudioIn() {
    if (converseRequestCase_ == 2) {
      return (com.google.protobuf.ByteString) converseRequest_;
    }
    return com.google.protobuf.ByteString.EMPTY;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (converseRequestCase_ == 1) {
      output.writeMessage(1, (com.google.assistant.embedded.v1alpha1.ConverseConfig) converseRequest_);
    }
    if (converseRequestCase_ == 2) {
      output.writeBytes(
          2, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) converseRequest_));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (converseRequestCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.google.assistant.embedded.v1alpha1.ConverseConfig) converseRequest_);
    }
    if (converseRequestCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(
            2, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) converseRequest_));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.assistant.embedded.v1alpha1.ConverseRequest)) {
      return super.equals(obj);
    }
    com.google.assistant.embedded.v1alpha1.ConverseRequest other = (com.google.assistant.embedded.v1alpha1.ConverseRequest) obj;

    boolean result = true;
    result = result && getConverseRequestCase().equals(
        other.getConverseRequestCase());
    if (!result) return false;
    switch (converseRequestCase_) {
      case 1:
        result = result && getConfig()
            .equals(other.getConfig());
        break;
      case 2:
        result = result && getAudioIn()
            .equals(other.getAudioIn());
        break;
      case 0:
      default:
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (converseRequestCase_) {
      case 1:
        hash = (37 * hash) + CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getConfig().hashCode();
        break;
      case 2:
        hash = (37 * hash) + AUDIO_IN_FIELD_NUMBER;
        hash = (53 * hash) + getAudioIn().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.assistant.embedded.v1alpha1.ConverseRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.assistant.embedded.v1alpha1.ConverseRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.assistant.embedded.v1alpha1.ConverseRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.assistant.embedded.v1alpha1.ConverseRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.assistant.embedded.v1alpha1.ConverseRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.assistant.embedded.v1alpha1.ConverseRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.assistant.embedded.v1alpha1.ConverseRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.assistant.embedded.v1alpha1.ConverseRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.assistant.embedded.v1alpha1.ConverseRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.assistant.embedded.v1alpha1.ConverseRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.assistant.embedded.v1alpha1.ConverseRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The top-level message sent by the client. Clients must send at least two, and
   * typically numerous `ConverseRequest` messages. The first message must
   * contain a `config` message and must not contain `audio_in` data. All
   * subsequent messages must contain `audio_in` data and must not contain a
   * `config` message.
   * </pre>
   *
   * Protobuf type {@code google.assistant.embedded.v1alpha1.ConverseRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.assistant.embedded.v1alpha1.ConverseRequest)
      com.google.assistant.embedded.v1alpha1.ConverseRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.assistant.embedded.v1alpha1.AssistantProto.internal_static_google_assistant_embedded_v1alpha1_ConverseRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.assistant.embedded.v1alpha1.AssistantProto.internal_static_google_assistant_embedded_v1alpha1_ConverseRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.assistant.embedded.v1alpha1.ConverseRequest.class, com.google.assistant.embedded.v1alpha1.ConverseRequest.Builder.class);
    }

    // Construct using com.google.assistant.embedded.v1alpha1.ConverseRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      converseRequestCase_ = 0;
      converseRequest_ = null;
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.assistant.embedded.v1alpha1.AssistantProto.internal_static_google_assistant_embedded_v1alpha1_ConverseRequest_descriptor;
    }

    public com.google.assistant.embedded.v1alpha1.ConverseRequest getDefaultInstanceForType() {
      return com.google.assistant.embedded.v1alpha1.ConverseRequest.getDefaultInstance();
    }

    public com.google.assistant.embedded.v1alpha1.ConverseRequest build() {
      com.google.assistant.embedded.v1alpha1.ConverseRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.google.assistant.embedded.v1alpha1.ConverseRequest buildPartial() {
      com.google.assistant.embedded.v1alpha1.ConverseRequest result = new com.google.assistant.embedded.v1alpha1.ConverseRequest(this);
      if (converseRequestCase_ == 1) {
        if (configBuilder_ == null) {
          result.converseRequest_ = converseRequest_;
        } else {
          result.converseRequest_ = configBuilder_.build();
        }
      }
      if (converseRequestCase_ == 2) {
        result.converseRequest_ = converseRequest_;
      }
      result.converseRequestCase_ = converseRequestCase_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.assistant.embedded.v1alpha1.ConverseRequest) {
        return mergeFrom((com.google.assistant.embedded.v1alpha1.ConverseRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.assistant.embedded.v1alpha1.ConverseRequest other) {
      if (other == com.google.assistant.embedded.v1alpha1.ConverseRequest.getDefaultInstance()) return this;
      switch (other.getConverseRequestCase()) {
        case CONFIG: {
          mergeConfig(other.getConfig());
          break;
        }
        case AUDIO_IN: {
          setAudioIn(other.getAudioIn());
          break;
        }
        case CONVERSEREQUEST_NOT_SET: {
          break;
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.assistant.embedded.v1alpha1.ConverseRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.assistant.embedded.v1alpha1.ConverseRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int converseRequestCase_ = 0;
    private java.lang.Object converseRequest_;
    public ConverseRequestCase
        getConverseRequestCase() {
      return ConverseRequestCase.forNumber(
          converseRequestCase_);
    }

    public Builder clearConverseRequest() {
      converseRequestCase_ = 0;
      converseRequest_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.assistant.embedded.v1alpha1.ConverseConfig, com.google.assistant.embedded.v1alpha1.ConverseConfig.Builder, com.google.assistant.embedded.v1alpha1.ConverseConfigOrBuilder> configBuilder_;
    /**
     * <pre>
     * The `config` message provides information to the recognizer that
     * specifies how to process the request.
     * The first `ConverseRequest` message must contain a `config` message.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha1.ConverseConfig config = 1;</code>
     */
    public com.google.assistant.embedded.v1alpha1.ConverseConfig getConfig() {
      if (configBuilder_ == null) {
        if (converseRequestCase_ == 1) {
          return (com.google.assistant.embedded.v1alpha1.ConverseConfig) converseRequest_;
        }
        return com.google.assistant.embedded.v1alpha1.ConverseConfig.getDefaultInstance();
      } else {
        if (converseRequestCase_ == 1) {
          return configBuilder_.getMessage();
        }
        return com.google.assistant.embedded.v1alpha1.ConverseConfig.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * The `config` message provides information to the recognizer that
     * specifies how to process the request.
     * The first `ConverseRequest` message must contain a `config` message.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha1.ConverseConfig config = 1;</code>
     */
    public Builder setConfig(com.google.assistant.embedded.v1alpha1.ConverseConfig value) {
      if (configBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        converseRequest_ = value;
        onChanged();
      } else {
        configBuilder_.setMessage(value);
      }
      converseRequestCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * The `config` message provides information to the recognizer that
     * specifies how to process the request.
     * The first `ConverseRequest` message must contain a `config` message.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha1.ConverseConfig config = 1;</code>
     */
    public Builder setConfig(
        com.google.assistant.embedded.v1alpha1.ConverseConfig.Builder builderForValue) {
      if (configBuilder_ == null) {
        converseRequest_ = builderForValue.build();
        onChanged();
      } else {
        configBuilder_.setMessage(builderForValue.build());
      }
      converseRequestCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * The `config` message provides information to the recognizer that
     * specifies how to process the request.
     * The first `ConverseRequest` message must contain a `config` message.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha1.ConverseConfig config = 1;</code>
     */
    public Builder mergeConfig(com.google.assistant.embedded.v1alpha1.ConverseConfig value) {
      if (configBuilder_ == null) {
        if (converseRequestCase_ == 1 &&
            converseRequest_ != com.google.assistant.embedded.v1alpha1.ConverseConfig.getDefaultInstance()) {
          converseRequest_ = com.google.assistant.embedded.v1alpha1.ConverseConfig.newBuilder((com.google.assistant.embedded.v1alpha1.ConverseConfig) converseRequest_)
              .mergeFrom(value).buildPartial();
        } else {
          converseRequest_ = value;
        }
        onChanged();
      } else {
        if (converseRequestCase_ == 1) {
          configBuilder_.mergeFrom(value);
        }
        configBuilder_.setMessage(value);
      }
      converseRequestCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * The `config` message provides information to the recognizer that
     * specifies how to process the request.
     * The first `ConverseRequest` message must contain a `config` message.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha1.ConverseConfig config = 1;</code>
     */
    public Builder clearConfig() {
      if (configBuilder_ == null) {
        if (converseRequestCase_ == 1) {
          converseRequestCase_ = 0;
          converseRequest_ = null;
          onChanged();
        }
      } else {
        if (converseRequestCase_ == 1) {
          converseRequestCase_ = 0;
          converseRequest_ = null;
        }
        configBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The `config` message provides information to the recognizer that
     * specifies how to process the request.
     * The first `ConverseRequest` message must contain a `config` message.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha1.ConverseConfig config = 1;</code>
     */
    public com.google.assistant.embedded.v1alpha1.ConverseConfig.Builder getConfigBuilder() {
      return getConfigFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The `config` message provides information to the recognizer that
     * specifies how to process the request.
     * The first `ConverseRequest` message must contain a `config` message.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha1.ConverseConfig config = 1;</code>
     */
    public com.google.assistant.embedded.v1alpha1.ConverseConfigOrBuilder getConfigOrBuilder() {
      if ((converseRequestCase_ == 1) && (configBuilder_ != null)) {
        return configBuilder_.getMessageOrBuilder();
      } else {
        if (converseRequestCase_ == 1) {
          return (com.google.assistant.embedded.v1alpha1.ConverseConfig) converseRequest_;
        }
        return com.google.assistant.embedded.v1alpha1.ConverseConfig.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * The `config` message provides information to the recognizer that
     * specifies how to process the request.
     * The first `ConverseRequest` message must contain a `config` message.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha1.ConverseConfig config = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.assistant.embedded.v1alpha1.ConverseConfig, com.google.assistant.embedded.v1alpha1.ConverseConfig.Builder, com.google.assistant.embedded.v1alpha1.ConverseConfigOrBuilder> 
        getConfigFieldBuilder() {
      if (configBuilder_ == null) {
        if (!(converseRequestCase_ == 1)) {
          converseRequest_ = com.google.assistant.embedded.v1alpha1.ConverseConfig.getDefaultInstance();
        }
        configBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.assistant.embedded.v1alpha1.ConverseConfig, com.google.assistant.embedded.v1alpha1.ConverseConfig.Builder, com.google.assistant.embedded.v1alpha1.ConverseConfigOrBuilder>(
                (com.google.assistant.embedded.v1alpha1.ConverseConfig) converseRequest_,
                getParentForChildren(),
                isClean());
        converseRequest_ = null;
      }
      converseRequestCase_ = 1;
      onChanged();;
      return configBuilder_;
    }

    /**
     * <pre>
     * The audio data to be recognized. Sequential chunks of audio data are sent
     * in sequential `ConverseRequest` messages. The first `ConverseRequest`
     * message must not contain `audio_in` data and all subsequent
     * `ConverseRequest` messages must contain `audio_in` data. The audio bytes
     * must be encoded as specified in `AudioInConfig`.
     * Audio must be sent at approximately real-time (16000 samples per second).
     * An error will be returned if audio is sent significantly faster or
     * slower.
     * </pre>
     *
     * <code>bytes audio_in = 2;</code>
     */
    public com.google.protobuf.ByteString getAudioIn() {
      if (converseRequestCase_ == 2) {
        return (com.google.protobuf.ByteString) converseRequest_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <pre>
     * The audio data to be recognized. Sequential chunks of audio data are sent
     * in sequential `ConverseRequest` messages. The first `ConverseRequest`
     * message must not contain `audio_in` data and all subsequent
     * `ConverseRequest` messages must contain `audio_in` data. The audio bytes
     * must be encoded as specified in `AudioInConfig`.
     * Audio must be sent at approximately real-time (16000 samples per second).
     * An error will be returned if audio is sent significantly faster or
     * slower.
     * </pre>
     *
     * <code>bytes audio_in = 2;</code>
     */
    public Builder setAudioIn(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  converseRequestCase_ = 2;
      converseRequest_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The audio data to be recognized. Sequential chunks of audio data are sent
     * in sequential `ConverseRequest` messages. The first `ConverseRequest`
     * message must not contain `audio_in` data and all subsequent
     * `ConverseRequest` messages must contain `audio_in` data. The audio bytes
     * must be encoded as specified in `AudioInConfig`.
     * Audio must be sent at approximately real-time (16000 samples per second).
     * An error will be returned if audio is sent significantly faster or
     * slower.
     * </pre>
     *
     * <code>bytes audio_in = 2;</code>
     */
    public Builder clearAudioIn() {
      if (converseRequestCase_ == 2) {
        converseRequestCase_ = 0;
        converseRequest_ = null;
        onChanged();
      }
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:google.assistant.embedded.v1alpha1.ConverseRequest)
  }

  // @@protoc_insertion_point(class_scope:google.assistant.embedded.v1alpha1.ConverseRequest)
  private static final com.google.assistant.embedded.v1alpha1.ConverseRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.assistant.embedded.v1alpha1.ConverseRequest();
  }

  public static com.google.assistant.embedded.v1alpha1.ConverseRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ConverseRequest>
      PARSER = new com.google.protobuf.AbstractParser<ConverseRequest>() {
    public ConverseRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConverseRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ConverseRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ConverseRequest> getParserForType() {
    return PARSER;
  }

  public com.google.assistant.embedded.v1alpha1.ConverseRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

