// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/assistant/embedded/v1alpha2/embedded_assistant.proto

package com.google.assistant.embedded.v1alpha2;

public final class AssistantProto {
  private AssistantProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_assistant_embedded_v1alpha2_AssistConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_assistant_embedded_v1alpha2_AssistConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_assistant_embedded_v1alpha2_AudioInConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_assistant_embedded_v1alpha2_AudioInConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_assistant_embedded_v1alpha2_AudioOutConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_assistant_embedded_v1alpha2_AudioOutConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_assistant_embedded_v1alpha2_DialogStateIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_assistant_embedded_v1alpha2_DialogStateIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_assistant_embedded_v1alpha2_AudioOut_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_assistant_embedded_v1alpha2_AudioOut_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_assistant_embedded_v1alpha2_DialogStateOut_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_assistant_embedded_v1alpha2_DialogStateOut_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_assistant_embedded_v1alpha2_AssistRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_assistant_embedded_v1alpha2_AssistRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_assistant_embedded_v1alpha2_AssistResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_assistant_embedded_v1alpha2_AssistResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_assistant_embedded_v1alpha2_SpeechRecognitionResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_assistant_embedded_v1alpha2_SpeechRecognitionResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_assistant_embedded_v1alpha2_DeviceConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_assistant_embedded_v1alpha2_DeviceConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_assistant_embedded_v1alpha2_DeviceAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_assistant_embedded_v1alpha2_DeviceAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_assistant_embedded_v1alpha2_DeviceLocation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_assistant_embedded_v1alpha2_DeviceLocation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n;google/assistant/embedded/v1alpha2/emb" +
      "edded_assistant.proto\022\"google.assistant." +
      "embedded.v1alpha2\032\034google/api/annotation" +
      "s.proto\032\030google/type/latlng.proto\"\335\002\n\014As" +
      "sistConfig\022L\n\017audio_in_config\030\001 \001(\01321.go" +
      "ogle.assistant.embedded.v1alpha2.AudioIn" +
      "ConfigH\000\022\024\n\ntext_query\030\006 \001(\tH\000\022L\n\020audio_" +
      "out_config\030\002 \001(\01322.google.assistant.embe" +
      "dded.v1alpha2.AudioOutConfig\022J\n\017dialog_s" +
      "tate_in\030\003 \001(\01321.google.assistant.embedde" +
      "d.v1alpha2.DialogStateIn\022G\n\rdevice_confi" +
      "g\030\004 \001(\01320.google.assistant.embedded.v1al" +
      "pha2.DeviceConfigB\006\n\004type\"\266\001\n\rAudioInCon" +
      "fig\022L\n\010encoding\030\001 \001(\0162:.google.assistant" +
      ".embedded.v1alpha2.AudioInConfig.Encodin" +
      "g\022\031\n\021sample_rate_hertz\030\002 \001(\005\"<\n\010Encoding" +
      "\022\030\n\024ENCODING_UNSPECIFIED\020\000\022\014\n\010LINEAR16\020\001" +
      "\022\010\n\004FLAC\020\002\"\343\001\n\016AudioOutConfig\022M\n\010encodin" +
      "g\030\001 \001(\0162;.google.assistant.embedded.v1al" +
      "pha2.AudioOutConfig.Encoding\022\031\n\021sample_r" +
      "ate_hertz\030\002 \001(\005\022\031\n\021volume_percentage\030\003 \001" +
      "(\005\"L\n\010Encoding\022\030\n\024ENCODING_UNSPECIFIED\020\000" +
      "\022\014\n\010LINEAR16\020\001\022\007\n\003MP3\020\002\022\017\n\013OPUS_IN_OGG\020\003" +
      "\"\217\001\n\rDialogStateIn\022\032\n\022conversation_state" +
      "\030\001 \001(\014\022\025\n\rlanguage_code\030\002 \001(\t\022K\n\017device_" +
      "location\030\005 \001(\01322.google.assistant.embedd" +
      "ed.v1alpha2.DeviceLocation\"\036\n\010AudioOut\022\022" +
      "\n\naudio_data\030\001 \001(\014\"\245\002\n\016DialogStateOut\022!\n" +
      "\031supplemental_display_text\030\001 \001(\t\022\032\n\022conv" +
      "ersation_state\030\002 \001(\014\022Z\n\017microphone_mode\030" +
      "\003 \001(\0162A.google.assistant.embedded.v1alph" +
      "a2.DialogStateOut.MicrophoneMode\022\031\n\021volu" +
      "me_percentage\030\004 \001(\005\"]\n\016MicrophoneMode\022\037\n" +
      "\033MICROPHONE_MODE_UNSPECIFIED\020\000\022\024\n\020CLOSE_" +
      "MICROPHONE\020\001\022\024\n\020DIALOG_FOLLOW_ON\020\002\"o\n\rAs" +
      "sistRequest\022B\n\006config\030\001 \001(\01320.google.ass" +
      "istant.embedded.v1alpha2.AssistConfigH\000\022" +
      "\022\n\010audio_in\030\002 \001(\014H\000B\006\n\004type\"\316\003\n\016AssistRe" +
      "sponse\022P\n\nevent_type\030\001 \001(\0162<.google.assi" +
      "stant.embedded.v1alpha2.AssistResponse.E" +
      "ventType\022?\n\taudio_out\030\003 \001(\0132,.google.ass" +
      "istant.embedded.v1alpha2.AudioOut\022G\n\rdev" +
      "ice_action\030\006 \001(\01320.google.assistant.embe" +
      "dded.v1alpha2.DeviceAction\022S\n\016speech_res" +
      "ults\030\002 \003(\0132;.google.assistant.embedded.v" +
      "1alpha2.SpeechRecognitionResult\022L\n\020dialo" +
      "g_state_out\030\005 \001(\01322.google.assistant.emb" +
      "edded.v1alpha2.DialogStateOut\"=\n\tEventTy" +
      "pe\022\032\n\026EVENT_TYPE_UNSPECIFIED\020\000\022\024\n\020END_OF" +
      "_UTTERANCE\020\001\"@\n\027SpeechRecognitionResult\022" +
      "\022\n\ntranscript\030\001 \001(\t\022\021\n\tstability\030\002 \001(\002\":" +
      "\n\014DeviceConfig\022\021\n\tdevice_id\030\001 \001(\t\022\027\n\017dev" +
      "ice_model_id\030\003 \001(\t\"+\n\014DeviceAction\022\033\n\023de" +
      "vice_request_json\030\001 \001(\t\"D\n\016DeviceLocatio" +
      "n\022*\n\013coordinates\030\001 \001(\0132\023.google.type.Lat" +
      "LngH\000B\006\n\004type2\210\001\n\021EmbeddedAssistant\022s\n\006A" +
      "ssist\0221.google.assistant.embedded.v1alph" +
      "a2.AssistRequest\0322.google.assistant.embe" +
      "dded.v1alpha2.AssistResponse(\0010\001B\206\001\n&com" +
      ".google.assistant.embedded.v1alpha2B\016Ass" +
      "istantProtoP\001ZJgoogle.golang.org/genprot" +
      "o/googleapis/assistant/embedded/v1alpha2" +
      ";embeddedb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.type.LatLngProto.getDescriptor(),
        }, assigner);
    internal_static_google_assistant_embedded_v1alpha2_AssistConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_assistant_embedded_v1alpha2_AssistConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_assistant_embedded_v1alpha2_AssistConfig_descriptor,
        new java.lang.String[] { "AudioInConfig", "TextQuery", "AudioOutConfig", "DialogStateIn", "DeviceConfig", "Type", });
    internal_static_google_assistant_embedded_v1alpha2_AudioInConfig_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_assistant_embedded_v1alpha2_AudioInConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_assistant_embedded_v1alpha2_AudioInConfig_descriptor,
        new java.lang.String[] { "Encoding", "SampleRateHertz", });
    internal_static_google_assistant_embedded_v1alpha2_AudioOutConfig_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_assistant_embedded_v1alpha2_AudioOutConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_assistant_embedded_v1alpha2_AudioOutConfig_descriptor,
        new java.lang.String[] { "Encoding", "SampleRateHertz", "VolumePercentage", });
    internal_static_google_assistant_embedded_v1alpha2_DialogStateIn_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_assistant_embedded_v1alpha2_DialogStateIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_assistant_embedded_v1alpha2_DialogStateIn_descriptor,
        new java.lang.String[] { "ConversationState", "LanguageCode", "DeviceLocation", });
    internal_static_google_assistant_embedded_v1alpha2_AudioOut_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_assistant_embedded_v1alpha2_AudioOut_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_assistant_embedded_v1alpha2_AudioOut_descriptor,
        new java.lang.String[] { "AudioData", });
    internal_static_google_assistant_embedded_v1alpha2_DialogStateOut_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_google_assistant_embedded_v1alpha2_DialogStateOut_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_assistant_embedded_v1alpha2_DialogStateOut_descriptor,
        new java.lang.String[] { "SupplementalDisplayText", "ConversationState", "MicrophoneMode", "VolumePercentage", });
    internal_static_google_assistant_embedded_v1alpha2_AssistRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_google_assistant_embedded_v1alpha2_AssistRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_assistant_embedded_v1alpha2_AssistRequest_descriptor,
        new java.lang.String[] { "Config", "AudioIn", "Type", });
    internal_static_google_assistant_embedded_v1alpha2_AssistResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_google_assistant_embedded_v1alpha2_AssistResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_assistant_embedded_v1alpha2_AssistResponse_descriptor,
        new java.lang.String[] { "EventType", "AudioOut", "DeviceAction", "SpeechResults", "DialogStateOut", });
    internal_static_google_assistant_embedded_v1alpha2_SpeechRecognitionResult_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_google_assistant_embedded_v1alpha2_SpeechRecognitionResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_assistant_embedded_v1alpha2_SpeechRecognitionResult_descriptor,
        new java.lang.String[] { "Transcript", "Stability", });
    internal_static_google_assistant_embedded_v1alpha2_DeviceConfig_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_google_assistant_embedded_v1alpha2_DeviceConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_assistant_embedded_v1alpha2_DeviceConfig_descriptor,
        new java.lang.String[] { "DeviceId", "DeviceModelId", });
    internal_static_google_assistant_embedded_v1alpha2_DeviceAction_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_google_assistant_embedded_v1alpha2_DeviceAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_assistant_embedded_v1alpha2_DeviceAction_descriptor,
        new java.lang.String[] { "DeviceRequestJson", });
    internal_static_google_assistant_embedded_v1alpha2_DeviceLocation_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_google_assistant_embedded_v1alpha2_DeviceLocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_assistant_embedded_v1alpha2_DeviceLocation_descriptor,
        new java.lang.String[] { "Coordinates", "Type", });
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.type.LatLngProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
