// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/assistant/embedded/v1alpha2/embedded_assistant.proto

package com.google.assistant.embedded.v1alpha2;

public interface AudioOutConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.assistant.embedded.v1alpha2.AudioOutConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * *Required* The encoding of audio data to be returned in all `audio_out`
   * messages.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha2.AudioOutConfig.Encoding encoding = 1;</code>
   */
  int getEncodingValue();
  /**
   * <pre>
   * *Required* The encoding of audio data to be returned in all `audio_out`
   * messages.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha2.AudioOutConfig.Encoding encoding = 1;</code>
   */
  com.google.assistant.embedded.v1alpha2.AudioOutConfig.Encoding getEncoding();

  /**
   * <pre>
   * *Required* The sample rate in Hertz of the audio data returned in
   * `audio_out` messages. Valid values are: 16000-24000.
   * </pre>
   *
   * <code>int32 sample_rate_hertz = 2;</code>
   */
  int getSampleRateHertz();

  /**
   * <pre>
   * *Required* Current volume setting of the device's audio output.
   * Valid values are 1 to 100 (corresponding to 1% to 100%).
   * </pre>
   *
   * <code>int32 volume_percentage = 3;</code>
   */
  int getVolumePercentage();
}
