// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/assistant/embedded/v1alpha2/embedded_assistant.proto

package com.google.assistant.embedded.v1alpha2;

public interface DialogStateInOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.assistant.embedded.v1alpha2.DialogStateIn)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * *Required* This field must always be set to the
   * [DialogStateOut.conversation_state][google.assistant.embedded.v1alpha2.DialogStateOut.conversation_state] value that was returned in the prior
   * `Assist` RPC. It should only be omitted (field not set) if there was no
   * prior `Assist` RPC because this is the first `Assist` RPC made by this
   * device after it was first setup and/or a factory-default reset.
   * </pre>
   *
   * <code>bytes conversation_state = 1;</code>
   */
  com.google.protobuf.ByteString getConversationState();

  /**
   * <pre>
   * *Required* Language of the request in
   * [IETF BCP 47 syntax](https://tools.ietf.org/html/bcp47). For example:
   * "en-US". If you have selected a language for this `device_id` using the
   * [Settings](https://developers.google.com/assistant/sdk/guides/assistant-settings)
   * menu in your phone's Google Assistant app, that selection will override
   * this value.
   * </pre>
   *
   * <code>string language_code = 2;</code>
   */
  java.lang.String getLanguageCode();
  /**
   * <pre>
   * *Required* Language of the request in
   * [IETF BCP 47 syntax](https://tools.ietf.org/html/bcp47). For example:
   * "en-US". If you have selected a language for this `device_id` using the
   * [Settings](https://developers.google.com/assistant/sdk/guides/assistant-settings)
   * menu in your phone's Google Assistant app, that selection will override
   * this value.
   * </pre>
   *
   * <code>string language_code = 2;</code>
   */
  com.google.protobuf.ByteString
      getLanguageCodeBytes();

  /**
   * <pre>
   * *Optional* Location of the device where the query originated.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha2.DeviceLocation device_location = 5;</code>
   */
  boolean hasDeviceLocation();
  /**
   * <pre>
   * *Optional* Location of the device where the query originated.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha2.DeviceLocation device_location = 5;</code>
   */
  com.google.assistant.embedded.v1alpha2.DeviceLocation getDeviceLocation();
  /**
   * <pre>
   * *Optional* Location of the device where the query originated.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha2.DeviceLocation device_location = 5;</code>
   */
  com.google.assistant.embedded.v1alpha2.DeviceLocationOrBuilder getDeviceLocationOrBuilder();
}
